multi-file

diff --git a/autofix b/autofix
--- a/autofix
+++ b/autofix
@@ -1,46 +1,26 @@
 #!/bin/bash
 
+set -euo pipefail
+TMP=".autofix"
+
 function usage {
 	echo "autofix filename.tex [glossary.tex]"
 }
 
-if test "x$1" == "xspace"
-then
-	SPACE=true
+SPACE=false
+ACCEPT=false
+while true
+do
+	case "$1" in
+	-s)	SPACE=true ;;
+	-a)	ACCEPT=true ;;
+	-*)	echo "Unknown option" >&2
+		usage
+		exit 2 ;;
+	*) break ;;
+	esac
 	shift
-else
-	SPACE=false
-fi
-
-MAIN=$1
-if test -z "$MAIN"
-then
-	usage
-	exit 1
-else
-	shift
-fi
-
-MAIN=$(echo "$MAIN" | sed 's/\.tex$//')
-
-if ! test -f "$MAIN.tex"
-then
-	usage
-	exit 2
-fi
-
-GLOSS=$1
-if test -z "$GLOSS"
-then
-	GLOSS=$MAIN
-else
-	shift
-fi
-
-
-TMP=tmp000
-
-set -e
+done
 
 if git rev-parse --git-dir > /dev/null 2>&1; then
 	INGIT=true
@@ -50,48 +30,60 @@ fi
 
 if $INGIT
 then
-	if ! git diff --exit-code $MAIN.tex >/dev/null
-	then
-		echo "WARNING: There are un-commited changes in $MAIN.tex"
-		COMMIT=false
-	else
-		COMMIT=true
-	fi
+	COMMIT=true
 else
 	COMMIT=false
 fi
 
-if $SPACE
-then
-	sed -E 's/((\.|,))[[:space:]]*$/\1/g' $MAIN.tex >$TMP.tex
-	mv $TMP.tex $MAIN.tex
-fi
-
-cp $MAIN.tex $TMP.tex
+for i in "$@"
+do
+	if ! test -f "$i"
+	then
+		echo "$i: file not found"
+		usage
+		exit 2
+	fi
+	if $COMMIT && ! git diff --exit-code $i >/dev/null
+	then
+		echo "WARNING: There are un-commited changes in $i (I won't propose to commit)"
+		COMMIT=false
+	fi
+	cp "$i" "$TMP.$i.backup"
+	cp "$i" "$TMP.$i"
+	echo -n >"$TMP.$i.msg"
+done
 
 function applysed {
-	line="$1"
-	test -z "$line" && return 0
-	echo "$line" | grep '^#' >/dev/null && return 0
-	HA=$(echo "$line" | sed -E 's/^.* # //')
-	if sed -E "/^[[:space:]]*%/! $line" $TMP.tex >$TMP.1.tex
+	FILE="$1"
+	shift
+	TOT="$(echo "$@")"
+	test -z "$TOT" && return 0
+	HA=$(echo "$TOT" | sed -E 's/^.* # //')
+	if sed "$@" $FILE >$FILE.tmp
 	then
-		if ! diff $TMP.1.tex $TMP.tex >/dev/null
+		if ! diff $FILE.tmp $FILE >/dev/null
 		then
-			echo "fix: $HA"
-			mv $TMP.1.tex $TMP.tex
+			echo "$FILE: fix: $HA"
+			echo "fix: $HA" >>$FILE.msg
+			mv  $FILE.tmp $FILE
 		fi
 	else
-		echo "sed failed for: $line"
+		echo "failed: sed $TOT $FILE"
 		exit 1
 	fi
 }
 
-function applyfixes {
-
+function applysimplefixes {
+	FILE="$1"
+	if ! test -f "$FILE"
+	then
+		 echo "no file in applysimplefixes" >&2
+		 exit 2
+	fi
 	while read -r line
 	do
-		applysed "$line"
+		echo "$line" | grep '^#' >/dev/null && continue  # if commented exit
+		applysed $FILE -E "/^[[:space:]]*%/! $line"
 	done <<'EOF'
 s/([[:space:]~(])e(|\.)(| )g(|\.)(|,|:)/\1\\eg./g # Change 'e.g.' to \eg.
 s/([[:space:]~(])i(|\.)(| )e(|\.)(|,|:)/\1\\ie./g # Change 'i.e.' to \ie.
@@ -105,7 +97,9 @@ s/(figure|Fig\.|fig\.)~(\\)/Figure~\2/g # Correcting capital letter on Figure
 s/(table|Tab\.|tab\.)~(\\)/Table~\2/g # Correcting capital letter on Table
 #s/([[:space:]])-([[:space:]])/\1---\2/g # Making dash a long dash
 EOF
+}
 
+function applydefs {
 	echo -n >$TMP.defs.tex
 	if grep '\\begin{document}' $TMP.tex >/dev/null
 	then
@@ -134,21 +128,41 @@ EOF
 	else
 		echo "warning: no begin{document} so I'm not adding any definitions"
 	fi
+}
 
-	echo -n >$TMP.acr.tex
-	grep "\\newacronym" $GLOSS.tex | while read -r line; do
-		COM=$(echo "$line" | sed -nE 's/^.*\\newacronym\{([^\}]*)\}.*/\1/p')
-		ACR=$(echo "$line" | sed -nE 's/^.*\\newacronym\{[^\}]*\}\{([^\}]*)\}.*/\1/p')
-		test -z "$COM" && continue
-		echo $ACR >>$TMP.acr.tex
-		applysed 's/([[:space:]+])'$ACR'([^}])/\1\\gls{'$COM'}\2/g # fixing acronym '$ACR''
-		applysed 's/^'$ACR'([^}])/\\gls{'$COM'}\1/g # fixing acronym '$ACR''
+
+
+function getacronyms {
+	FILE="$1"
+	if ! test -f "$FILE"
+	then
+		 echo "no file in applysimplefixes" >&2
+		 exit 2
+	fi
+	echo "get acronyms from $FILE"
+	sed -n -e 's/^.*\\newacronym{\([^}]*\)}{\([^}]*\)}.*$/\1 %%% \2/p' "$FILE" >>$TMP.acr.def
+}
+
+function applyacronyms {
+	FILE="$1"
+	if ! test -f "$FILE"
+	then
+		 echo "no file in applysimplefixes" >&2
+		 exit 2
+	fi
+	sed 's|\(.*\) %%% \(.*\)|s/\\([^{]\\)\2\\b/\\1\\gls{\1}/g # Fixing acronym \2|' $TMP.acr.def |
+	while read -r line; do
+		applysed "$FILE" "$line"
 	done
+}
 
-	ACRS=$(sed -e 's/\\gls{[^}]*}//g' -e '/\\newacronym/d' $TMP.tex |
+function printmissingacr {
+	sed -e 's/\\gls{[^}]*}//g' -e '/\\newacronym/d' $TMP.tex |
 		grep -o '\b[[:upper:]][[:upper:]][[:upper:]]*\b' |
-		sort | uniq |
-		comm - <(sort $TMP.acr.tex) -23 |
+		sort | uniq >$TMP.acr.cur
+	sort $TMP.acr.tex >$TMP.acr.def
+	ACRS=$(
+		comm $TMP.acr.cur $TMP.acr.def -23 |
 		paste -sd ',' -
 	)
 	if ! test -z "$ACRS"
@@ -156,6 +170,24 @@ EOF
 		echo "warning: Consider adding these acronyms: $ACRS"
 	fi
 }
+
+for i in "$@"
+do
+	applysimplefixes "$TMP.$i"
+done
+
+echo -n >$TMP.acr.def
+for i in "$@"
+do
+	getacronyms "$TMP.$i"
+done
+
+for i in "$@"
+do
+	applyacronyms "$TMP.$i"
+done
+
+exit 2;
 
 applyfixes | tee $TMP.0.msg
 
